// <auto-generated />
namespace Nsk.OnlineStore.Web.Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NorthwindCustomerId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NorthwindCustomerId));
        
        string IMigrationMetadata.Id
        {
            get { return "201507031458316_NorthwindCustomerId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
